version: '2'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postresql/data
  identity-service:
    image: qassimov/identity-service:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=https://app.carsties.com
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
      - VIRTUAL_HOST=id.carsties.com
      # - LETSENCRYPT_HOST=idtest.trycatchlearn.com
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./devcerts:/etc/nginx/certs
  # acme-companion:
  #   image: nginxproxy/acme-companion
  #   container_name: nginx-proxy-acme
  #   environment:
  #     - DEFAULT_EMAIL=CHANGEME@CHANGEME.com
  #   volumes_from:
  #     - nginx-proxy
  #   volumes:
  #     - certs:/etc/nginx/certs:rw
  #     - acme:/etc/acme.sh
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  pgdata:
  conf:
  vhost:
  html:
  certs:
  # acme: