apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-service
spec:
  selector:
    matchLabels:
      app: auction-service
  template:
    metadata:
      labels:
        app: auction-service
    spec:
      containers:
      - name: auction-service
        image: qassimov/auction-service
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: RabbitMq__Host
            value: rabbit-clusterip
          - name: RabbitMq__Username
            value: rabbit
          - name: RabbitMq__Password
            value: rabbit
          - name: ConnectionStrings__DefaultConnection
            value: Server=postgres-clusterip:5432;User Id=postgres;Password=postgrespw;Database=auctions
          - name: IdentityServiceUrl
            value: https://id.carsties.com
          - name: Kestrel__Endpoints__Grpc__Protocols
            value: Http2
          - name: Kestrel__Endpoints__Grpc__Url
            value: http://+:7777
          - name: Kestrel__Endpoints__WebApi__Protocols
            value: Http1
          - name: Kestrel__Endpoints__WebApi__Url
            value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: auction-clusterip
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
    name: web
  - port: 7777
    targetPort: 7777
    name: grpc
