apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: qassimov/identity-service
        imagePullPolicy: Never
        env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: identity-secret
                key: connString
          - name: ClientApp
            value: https://app.carsties.com
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /app/share
          name: identityshare
      volumes:
        - name: identityshare
          persistentVolumeClaim:
            claimName: identity-claim
---
apiVersion: v1
kind: Service
metadata:
  name: identity-clusterip
spec:
  type: ClusterIP
  selector:
    app: identity-service
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: identity-lb
spec:
  type: LoadBalancer
  selector:
    app: identity-service
  ports:
  - port: 80
    targetPort: 80
