apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: qassimov/identity-service
          imagePullPolicy: Always
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: identity-secret
                  key: connString
            - name: ClientApp
              value: http://app.carsties.com
            - name: ClientSecret
              valueFrom:
                secretKeyRef:
                  name: identity-secret
                  key: clientSecret
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app/share
              name: identityshare
      volumes:
        - name: identityshare
          persistentVolumeClaim:
            claimName: identity-claim
---
apiVersion: v1
kind: Service
metadata:
  name: identity-clusterip
spec:
  type: ClusterIP
  selector:
    app: identity-service
  ports:
    - port: 80
      targetPort: 80
