name: apply-k8s

on:
  workflow_dispatch:
  push:
    branches: ['master']
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: kubectl apply infra
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: |
          curl https://sdk.cloud.google.com > install.sh
          bash install.sh --disable-prompts
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud components update kubectl
          echo "$GCLOUD_SERVICE_KEY" >> service-account.json
          gcloud auth activate-service-account --key-file service-account.json
          gcloud config set project k8s-deployment-382006
          gcloud config set compute/region europe-west1
          gcloud config set compute/zone europe-west1-b
          gcloud container clusters get-credentials carsties-k8s
          kubectl apply -f infra/K8S && kubectl apply -f infra/prod-k8s
