name: deploy-notify

on:
  workflow_dispatch:
  push:
    branches: ['master']
    paths:
      - 'src/NotificationService/**'

env:
  REGISTRY_IMAGE: qassimv/notify-service
  DOCKERFILE: src/NotificationService/Dockerfile
  DEPLOYMENT_NAME: notify-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: '{{defaultContext}}'
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:latest
      - name: restart kubernetes deployment
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: |
          curl https://sdk.cloud.google.com > install.sh
          bash install.sh --disable-prompts
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud components update kubectl
          echo "$GCLOUD_SERVICE_KEY" >> service-account.json
          gcloud auth activate-service-account --key-file service-account.json
          gcloud config set project k8s-deployment-382006
          gcloud container clusters get-credentials cluster
          kubectl rollout restart deployment ${{ env.DEPLOYMENT_NAME }}
